[build]
  # Directorio de publicación (donde están los archivos estáticos)
  publish = "."
  
  # Comando de build (opcional, ya que es un sitio estático)
  command = "echo 'No build needed - static site'"

[[headers]]
  # Aplicar headers a todos los archivos
  for = "/*"
  [headers.values]
    # Habilitar CORS para archivos 3D
    Access-Control-Allow-Origin = "*"
    # Cache para assets 3D
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Headers específicos para archivos 3D
  for = "*.ksplat"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.ply"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.fbx"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

# Redirects para SPA (Single Page Application)
[[redirects]]
  from = "/views/*"
  to = "/views/:splat"
  status = 200

# Configuración de formularios (si los necesitas)
[build.environment]
  NODE_VERSION = "18"