[build]
  # Directorio de publicación (raíz del proyecto donde está index.html)
  publish = "."
  
  # Comando de build (sitio estático)
  command = "echo 'Static site deployment'"

[[headers]]
  # Aplicar headers a todos los archivos
  for = "/*"
  [headers.values]
    # Habilitar CORS para archivos 3D
    Access-Control-Allow-Origin = "*"
    # Cache para assets 3D
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Headers específicos para archivos 3D
  for = "*.ksplat"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.ply"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.fbx"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

# Sin redirects - servir archivos estáticos directamente

# Configuración de formularios (si los necesitas)
[build.environment]
  NODE_VERSION = "18"